### ISSUE TITLE
[BUG] Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by PeterLjunggren** [bluefireteam/photo_view#489]
When I open Photoview and dont do anything bot pops the screen I get an error:

_FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)_

If I triggers some events, e.g. panning, scaling ,it goes well.

[✓] Flutter (Channel master, 2.6.0-12.0.pre.869, on macOS 11.4 20F71 darwin-x64, locale sv-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)

A known behaviour?

**Comment by bounty1342** [comment]
Google would have helped you : [LMGTFY](https://letmegooglethat.com/?q=https%3A%2F%2Flmgtfy.app%2F%3Fq%3DLooking%2Bup%2Ba%2Bdeactivated%2Bwidget%2527s%2Bancestor%2Bis%2Bunsafe)

In short: your context change and photo_view has been disposed.

**Comment by YofarDev** [comment]
I had this error too and could not find any answer on google which fix it. But I figured out after switching flutter channel to stable fixed it (I was using channel master), you don't get the error anymore.

```
flutter channel stable
flutter upgrade --force
```

**Comment by luomo-pro** [comment]
I have also encountered this problem. I use the master version of flutter.
Is there any progress on this issue now?

**Comment by laowenlu** [comment]
the same error:

```
FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)
```

**Comment by DonWasyl** [comment]
The same on Flutter 2.9.0 (master channel)

**Comment by DonWasyl** [comment]
yyy.... It looks like I fixed it.. But I won't push Pull request with that because it's very weird...

https://github.com/DonWasyl/photo_view/commit/f0b3e79a988a701ffe5ac06b37f22c3a5bd24c3e

When I put `print(_scaleAnimationController)` or this condition it started work, but without that (or `print()`) stop...
If someone have better solution feel free

**Comment by YDA93** [comment]
Same error here.
Any work-around please?
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale en-KW)
    • Flutter version 2.10.0 at /Users/yousefalmutairi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (2 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yousefalmutairi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • SM G965F (mobile) • 2449cd411a1c7ece          • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)   • 00008030-000134911482802E • ios            • iOS 15.3 19D50
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 97.0.4692.99
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by YDA93** [comment]
Please have a look into stack trace:
<details>
<summary>Stack trace</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
#1      Element._debugCheckStateIsActiveForAncestorLookup
#2      Element.getElementForInheritedWidgetOfExactType
#3      TickerMode.getNotifier
#4      TickerProviderStateMixin._updateTickerModeNotifier
#5      TickerProviderStateMixin.createTicker
#6      new AnimationController
#7      PhotoViewCoreState._scaleAnimationController
#8      PhotoViewCoreState._scaleAnimationController (package:photo_view/src/core/photo_view_core.dart)
#9      PhotoViewCoreState.dispose
#10     StatefulElement.unmount
#11     _InactiveElements._unmount
#12     _InactiveElements._unmount.<anonymous closure>
#13     ComponentElement.visitChildren
#14     _InactiveElements._unmount
#15     _InactiveElements._unmount.<anonymous closure>
#16     _LayoutBuilderElement.visitChildren
#17     _InactiveElements._unmount
#18     _InactiveElements._unmount.<anonymous closure>
#19     ComponentElement.visitChildren
#20     _InactiveElements._unmount
#21     _InactiveElements._unmount.<anonymous closure>
#22     SingleChildRenderObjectElement.visitChildren
#23     _InactiveElements._unmount
#24     _InactiveElements._unmount.<anonymous closure>
#25     SingleChildRenderObjectElement.visitChildren
#26     _InactiveElements._unmount
#27     _InactiveElements._unmount.<anonymous closure>
#28     SingleChildRenderObjectElement.visitChildren
#29     _InactiveElements._unmount
#30     _InactiveElements._unmount.<anonymous closure>
#31     ComponentElement.visitChildren
#32     _InactiveElements._unmount
#33     _InactiveElements._unmount.<anonymous closure>
#34     ComponentElement.visitChildren
#35     _InactiveElements._unmount
#36     _InactiveElements._unmount.<anonymous closure>
#37     ComponentElement.visitChildren
#38     _InactiveElements._unmount
#39     _InactiveElements._unmount.<anonymous closure>
#40     ComponentElement.visitChildren
#41     _InactiveElements._unmount
#42     _InactiveElements._unmount.<anonymous closure>
#43     List.forEach (dart:core-patch/growable_array.dart:433:8)
#44     SliverMultiBoxAdaptorElement.visitChildren
#45     _InactiveElements._unmount
#46     _InactiveElements._unmount.<anonymous closure>
#47     SingleChildRenderObjectElement.visitChildren
#48     _InactiveElements._unmount
#49     _InactiveElements._unmount.<anonymous closure>
#50     ComponentElement.visitChildren
#51     _InactiveElements._unmount
#52     _InactiveElements._unmount.<anonymous closure>
#53     MultiChildRenderObjectElement.visitChildren
#54     _InactiveElements._unmount
#55     _InactiveElements._unmount.<anonymous closure>
#56     SingleChildRenderObjectElement.visitChildren
#57     _InactiveElements._unmount
#58     _InactiveElements._unmount.<anonymous closure>
#59     SingleChildRenderObjectElement.visitChildren
#60     _InactiveElements._unmount
#61     _InactiveElements._unmount.<anonymous closure>
#62     SingleChildRenderObjectElement.visitChildren
#63     _InactiveElements._unmount
#64     _InactiveElements._unmount.<anonymous closure>
#65     SingleChildRenderObjectElement.visitChildren
#66     _InactiveElements._unmount
#67     _InactiveElements._unmount.<anonymous closure>
#68     ComponentElement.visitChildren
#69     _InactiveElements._unmount
#70     _InactiveElements._unmount.<anonymous closure>
#71     SingleChildRenderObjectElement.visitChildren
#72     _InactiveElements._unmount
#73     _InactiveElements._unmount.<anonymous closure>
#74     ComponentElement.visitChildren
#75     _InactiveElements._unmount
#76     _InactiveElements._unmount.<anonymous closure>
#77     SingleChildRenderObjectElement.visitChildren
#78     _InactiveElements._unmount
#79     _InactiveElements._unmount.<anonymous closure>
#80     ComponentElement.visitChildren
#81     _InactiveElements._unmount
#82     _InactiveElements._unmount.<anonymous closure>
#83     ComponentElement.visitChildren
#84     _InactiveElements._unmount
#85     _InactiveElements._unmount.<anonymous closure>
#86     ComponentElement.visitChildren
#87     _InactiveElements._unmount
#88     _InactiveElements._unmount.<anonymous closure>
#89     ComponentElement.visitChildren
#90     _InactiveElements._unmount
#91     _InactiveElements._unmount.<anonymous closure>
#92     ComponentElement.visitChildren
#93     _InactiveElements._unmount
#94     _InactiveElements._unmount.<anonymous closure>
#95     ComponentElement.visitChildren
#96     _InactiveElements._unmount
#97     _InactiveElements._unmount.<anonymous closure>
#98     ComponentElement.visitChildren
#99     _InactiveElements._unmount
#100    _InactiveElements._unmount.<anonymous closure>
#101    ComponentElement.visitChildren
#102    _InactiveElements._unmount
#103    _InactiveElements._unmount.<anonymous closure>
#104    SingleChildRenderObjectElement.visitChildren
#105    _InactiveElements._unmount
#106    _InactiveElements._unmount.<anonymous closure>
#107    ComponentElement.visitChildren
#108    _InactiveElements._unmount
#109    _InactiveElements._unmount.<anonymous closure>
#110    SingleChildRenderObjectElement.visitChildren
#111    _InactiveElements._unmount
#112    _InactiveElements._unmount.<anonymous closure>
#113    ComponentElement.visitChildren
#114    _InactiveElements._unmount
#115    _InactiveElements._unmount.<anonymous closure>
#116    ComponentElement.visitChildren
#117    _InactiveElements._unmount
#118    _InactiveElements._unmount.<anonymous closure>
#119    ComponentElement.visitChildren
#120    _InactiveElements._unmount
#121    _InactiveElements._unmount.<anonymous closure>
#122    _LayoutBuilderElement.visitChildren
#123    _InactiveElements._unmount
#124    _InactiveElements._unmount.<anonymous closure>
#125    ComponentElement.visitChildren
#126    _InactiveElements._unmount
#127    _InactiveElements._unmount.<anonymous closure>
#128    ComponentElement.visitChildren
#129    _InactiveElements._unmount
#130    _InactiveElements._unmount.<anonymous closure>
#131    ComponentElement.visitChildren
#132    _InactiveElements._unmount
#133    _InactiveElements._unmount.<anonymous closure>
#134    MultiChildRenderObjectElement.visitChildren
#135    _InactiveElements._unmount
#136    _InactiveElements._unmount.<anonymous closure>
#137    ComponentElement.visitChildren
#138    _InactiveElements._unmount
#139    _InactiveElements._unmount.<anonymous closure>
#140    ComponentElement.visitChildren
#141    _InactiveElements._unmount
#142    _InactiveElements._unmount.<anonymous closure>
#143    ComponentElement.visitChildren
#144    _InactiveElements._unmount
#145    _InactiveElements._unmount.<anonymous closure>
#146    SingleChildRenderObjectElement.visitChildren
#147    _InactiveElements._unmount
#148    _InactiveElements._unmount.<anonymous closure>
#149    ComponentElement.visitChildren
#150    _InactiveElements._unmount
#151    _InactiveElements._unmount.<anonymous closure>
#152    SingleChildRenderObjectElement.visitChildren
#153    _InactiveElements._unmount
#154    _InactiveElements._unmount.<anonymous closure>
#155    ComponentElement.visitChildren
#156    _InactiveElements._unmount
#157    _InactiveElements._unmount.<anonymous closure>
#158    ComponentElement.visitChildren
#159    _InactiveElements._unmount
#160    _InactiveElements._unmount.<anonymous closure>
#161    ComponentElement.visitChildren
#162    _InactiveElements._unmount
#163    _InactiveElements._unmount.<anonymous closure>
#164    ComponentElement.visitChildren
#165    _InactiveElements._unmount
#166    _InactiveElements._unmount.<anonymous closure>
#167    ComponentElement.visitChildren
#168    _InactiveElements._unmount
#169    _InactiveElements._unmount.<anonymous closure>
#170    ComponentElement.visitChildren
#171    _InactiveElements._unmount
#172    _InactiveElements._unmount.<anonymous closure>
#173    ComponentElement.visitChildren
#174    _InactiveElements._unmount
#175    _InactiveElements._unmount.<anonymous closure>
#176    ComponentElement.visitChildren
#177    _InactiveElements._unmount
#178    _InactiveElements._unmount.<anonymous closure>
#179    SingleChildRenderObjectElement.visitChildren
#180    _InactiveElements._unmount
#181    _InactiveElements._unmount.<anonymous closure>
#182    ComponentElement.visitChildren
#183    _InactiveElements._unmount
#184    _InactiveElements._unmount.<anonymous closure>
#185    ComponentElement.visitChildren
#186    _InactiveElements._unmount
#187    _InactiveElements._unmount.<anonymous closure>
#188    ComponentElement.visitChildren
#189    _InactiveElements._unmount
#190    _InactiveElements._unmount.<anonymous closure>
#191    SingleChildRenderObjectElement.visitChildren
#192    _InactiveElements._unmount
#193    _InactiveElements._unmount.<anonymous closure>
#194    ComponentElement.visitChildren
#195    _InactiveElements._unmount
#196    _InactiveElements._unmount.<anonymous closure>
#197    SingleChildRenderObjectElement.visitChildren
#198    _InactiveElements._unmount
#199    _InactiveElements._unmount.<anonymous closure>
#200    ComponentElement.visitChildren
#201    _InactiveElements._unmount
#202    _InactiveElements._unmount.<anonymous closure>
#203    SingleChildRenderObjectElement.visitChildren
#204    _InactiveElements._unmount
#205    _InactiveElements._unmount.<anonymous closure>
#206    ComponentElement.visitChildren
#207    _InactiveElements._unmount
#208    _InactiveElements._unmount.<anonymous closure>
#209    ComponentElement.visitChildren
#210    _InactiveElements._unmount
#211    _InactiveElements._unmount.<anonymous closure>
#212    SingleChildRenderObjectElement.visitChildren
#213    _InactiveElements._unmount
#214    _InactiveElements._unmount.<anonymous closure>
#215    ComponentElement.visitChildren
#216    _InactiveElements._unmount
#217    _InactiveElements._unmount.<anonymous closure>
#218    ComponentElement.visitChildren
#219    _InactiveElements._unmount
#220    _InactiveElements._unmount.<anonymous closure>
#221    ComponentElement.visitChildren
#222    _InactiveElements._unmount
#223    _InactiveElements._unmount.<anonymous closure>
#224    SingleChildRenderObjectElement.visitChildren
#225    _InactiveElements._unmount
#226    _InactiveElements._unmount.<anonymous closure>
#227    SingleChildRenderObjectElement.visitChildren
#228    _InactiveElements._unmount
#229    _InactiveElements._unmount.<anonymous closure>
#230    SingleChildRenderObjectElement.visitChildren
#231    _InactiveElements._unmount
#232    _InactiveElements._unmount.<anonymous closure>
#233    ComponentElement.visitChildren
#234    _InactiveElements._unmount
#235    _InactiveElements._unmount.<anonymous closure>
#236    ComponentElement.visitChildren
#237    _InactiveElements._unmount
#238    _InactiveElements._unmount.<anonymous closure>
#239    ComponentElement.visitChildren
#240    _InactiveElements._unmount
#241    _InactiveElements._unmount.<anonymous closure>
#242    ComponentElement.visitChildren
#243    _InactiveElements._unmount
#244    _InactiveElements._unmount.<anonymous closure>
#245    ComponentElement.visitChildren
#246    _InactiveElements._unmount
#247    _InactiveElements._unmount.<anonymous closure>
#248    ComponentElement.visitChildren
#249    _InactiveElements._unmount
#250    _InactiveElements._unmount.<anonymous closure>
#251    ComponentElement.visitChildren
#252    _InactiveElements._unmount
#253    _InactiveElements._unmount.<anonymous closure>
#254    SingleChildRenderObjectElement.visitChildren
#255    _InactiveElements._unmount
#256    _InactiveElements._unmount.<anonymous closure>
#257    SingleChildRenderObjectElement.visitChildren
#258    _InactiveElements._unmount
#259    _InactiveElements._unmount.<anonymous closure>
#260    ComponentElement.visitChildren
#261    _InactiveElements._unmount
#262    _InactiveElements._unmount.<anonymous closure>
#263    ComponentElement.visitChildren
#264    _InactiveElements._unmount
#265    _InactiveElements._unmount.<anonymous closure>
#266    SingleChildRenderObjectElement.visitChildren
#267    _InactiveElements._unmount
#268    _InactiveElements._unmount.<anonymous closure>
#269    SingleChildRenderObjectElement.visitChildren
#270    _InactiveElements._unmount
#271    _InactiveElements._unmount.<anonymous closure>
#272    ComponentElement.visitChildren
#273    _InactiveElements._unmount
#274    _InactiveElements._unmount.<anonymous closure>
#275    SingleChildRenderObjectElement.visitChildren
#276    _InactiveElements._unmount
#277    _InactiveElements._unmount.<anonymous closure>
#278    ComponentElement.visitChildren
#279    _InactiveElements._unmount
#280    _InactiveElements._unmount.<anonymous closure>
#281    ComponentElement.visitChildren
#282    _InactiveElements._unmount
#283    _InactiveElements._unmount.<anonymous closure>
#284    ComponentElement.visitChildren
#285    _InactiveElements._unmount
#286    _InactiveElements._unmount.<anonymous closure>
#287    ComponentElement.visitChildren
#288    _InactiveElements._unmount
#289    _InactiveElements._unmount.<anonymous closure>
#290    ComponentElement.visitChildren
#291    _InactiveElements._unmount
#292    _InactiveElements._unmount.<anonymous closure>
#293    ComponentElement.visitChildren
#294    _InactiveElements._unmount
#295    _InactiveElements._unmount.<anonymous closure>
#296    SingleChildRenderObjectElement.visitChildren
#297    _InactiveElements._unmount
#298    _InactiveElements._unmount.<anonymous closure>
#299    ComponentElement.visitChildren
#300    _InactiveElements._unmount
#301    _InactiveElements._unmount.<anonymous closure>
#302    ComponentElement.visitChildren
#303    _InactiveElements._unmount
#304    _InactiveElements._unmount.<anonymous closure>
#305    ComponentElement.visitChildren
#306    _InactiveElements._unmount
#307    _InactiveElements._unmount.<anonymous closure>
#308    ComponentElement.visitChildren
#309    _InactiveElements._unmount
#310    _InactiveElements._unmount.<anonymous closure>
#311    ComponentElement.visitChildren
#312    _InactiveElements._unmount
#313    _InactiveElements._unmount.<anonymous closure>
#314    SingleChildRenderObjectElement.visitChildren
#315    _InactiveElements._unmount
#316    _InactiveElements._unmount.<anonymous closure>
#317    ComponentElement.visitChildren
#318    _InactiveElements._unmount
#319    _InactiveElements._unmount.<anonymous closure>
#320    ComponentElement.visitChildren
#321    _InactiveElements._unmount
#322    _InactiveElements._unmount.<anonymous closure>
#323    ComponentElement.visitChildren
#324    _InactiveElements._unmount
#325    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#326    _InactiveElements._unmountAll
#327    BuildOwner.lockState
#328    BuildOwner.finalizeTree
#329    WidgetsBinding.drawFrame
#330    RendererBinding._handlePersistentFrameCallback
#331    SchedulerBinding._invokeFrameCallback
#332    SchedulerBinding.handleDrawFrame
#333    SchedulerBinding._handleDrawFrame
#337    _invoke (dart:ui/hooks.dart:151:10)
#338    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#339    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

```
</details>

**Comment by karvulf** [comment]
I created a pull request for this issue -> https://github.com/bluefireteam/photo_view/pull/499

**Comment by renancaraujo** [comment]
> I created a pull request for this issue -> #499

Thanks for the contribution!

**Comment by bibek624** [comment]
I have the same error. Any solution for this?

**Comment by holisticapps** [comment]
I have the same error.

**Comment by peterhijma** [comment]
Me too. Is it possible to do the new release soonish as the PR with the fix is already merged, right?

**Comment by wizebaseLLC** [comment]
Any hope for this to be fixed soon, or at least give a timeframe?  Updating to the latest stable branch breaks this.

**Comment by karvulf** [comment]
Well, for the time being, you could change your pubspec.yaml to

```yaml
...
photo_view:
    git: https://github.com/bluefireteam/photo_view.git
...
```

**Comment by delegate-it** [comment]
> ```yaml
> 
> photo_view:
>     git: https://github.com/bluefireteam/photo_view.git
> ```

I added the below to my pubspec.yaml
```

  photo_view: 
    git: https://github.com/bluefireteam/photo_view.git
```
I get the following message when I pub get
flutter pub get
Running "flutter pub get" in...               
Because flutter_chat_ui 1.5.5 depends on photo_view ^0.13.0 and no versions of flutter_chat_ui match >1.5.5 <2.0.0, flutter_chat_ui ^1.5.5 requires photo_view from hosted.
So, because depends on both flutter_chat_ui ^1.5.5 and photo_view from git, version solving failed.
pub get failed (1; So, because skillz_trader_app depends on both flutter_chat_ui ^1.5.5 and photo_view from git, version solving failed.)
exit code 1

**Comment by DeliriousLee** [comment]
this might be useful
``` 
photo_view-0.13.0/lib/src/core/photo_view_core.dart/PhotoViewCoreState > dispose():
  @override
  void dispose() {
    _scaleAnimationController.removeStatusListener(onAnimationStatus);
    _scaleAnimationController.dispose();
    _positionAnimationController.dispose();
    _rotationAnimationController.dispose();
    super.dispose();
}
```
Change this to
```
  @override
  void dispose() {
    super.dispose();
    _scaleAnimationController.removeStatusListener(onAnimationStatus);
    _scaleAnimationController.dispose();
    _positionAnimationController.dispose();
    _rotationAnimationController.dispose();
}
```
it seems that dispose controller at the wrong time

**Comment by DeD1rk** [comment]
@delegate-it you might try using [`dependency_overrides`](https://dart.dev/tools/pub/dependencies#dependency-overrides). Another suggestions is to specify a specific commit in this repo, rather than just the latest on master channel:
```yaml
dependency_overrides:
  photo_view: 
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b
```

**Comment by intraector** [comment]
same error with Flutter 2.10.3

**Comment by imugaibel** [comment]
when zoom in/out images no error.

**Comment by klivin** [comment]
Hi there, hoping you can update with this merge...dependencies are failing that use this repo ie flutter_quill because of this one!  Thanks

**Comment by renancaraujo** [comment]
0.14.0 is out, See #505

**Comment by premkumarcsn** [comment]
Same exception in Flutter version 3 too 

FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)

**Comment by andreBalh** [comment]
Upgrade to version `0.14.0` and it should work @premkumarcsn

**Comment by premkumarcsn** [comment]
Thank you, I will try now
